-- SP PARA DropDownList DE SEDES
CREATE PROCEDURE SP_Sedes AS
BEGIN
	SELECT * FROM Sede
END

-- SP PARA DropDownList DE ESPECIALIDADES
CREATE PROCEDURE SP_Especialidades AS
BEGIN
	SELECT * FROM Especialidades
END